// Class automatically generated by Dev-C++ New Class wizard

#ifndef AUDIOPORTOUT_H
#define AUDIOPORTOUT_H

#include "module.h" // inheriting class's header file

/*
 * Interfejs wyjscia karty dzwiekowej
 */
class AudioPortOut : public Module {
	public:
		AudioPortOut();
		~AudioPortOut();
};

#endif // AUDIOPORTOUT_H
