// Class automatically generated by Dev-C++ New Class wizard

#ifndef AUDIOPORTIN_H
#define AUDIOPORTIN_H

#include "module.h" // inheriting class's header file

/**
 * No description
 */
class AudioPortIn : public Module {
	public:
		AudioPortIn();
		~AudioPortIn();

	private:
		Output oLeft;
		Output oRight;
};

#endif // AUDIOPORTIN_H
