// Class automatically generated by Dev-C++ New Class wizard

#include "audioportout.h" // class's header file

// class constructor
AudioPortOut::AudioPortOut() {
	type = "AudioPortOut";
	addInput("audio in");
}

// class destructor
AudioPortOut::~AudioPortOut() {
}
