// Class automatically generated by Dev-C++ New Class wizard

#ifndef CONSTANT_H
#define CONSTANT_H

#include "module.h" // inheriting class's header file

/**
 * No description
 */
class Constant : public Module {
	public:
		// class constructor
		Constant();
		// class destructor
		~Constant();
		void process();
		
	private:
		int oValue;	// indeks wyjscia
		int pValue; // indeks parametru
		float oldValue;
		
};

#endif // CONSTANT_H
