// Class automatically generated by Dev-C++ New Class wizard

#ifndef MUL_H
#define MUL_H

#include "module.h" // inheriting class's header file

/**
 * Modul mnozenia. Mnozy skalarnie dwa sygnaly wejsciowe.
 */
class Gain : public Module
{
	public:
		// class constructor
		Gain();
		// class destructor
		~Gain();
		void process();
	
	private:
		int iIn, oOut, pGain;
};

#endif // MUL_H
