// Class automatically generated by Dev-C++ New Class wizard

#ifndef SUM_H
#define SUM_H

#include "module.h" // inheriting class's header file

/**
 * No description
 */
class Sum : public Module
{
	public:
		// class constructor
		Sum();
		// class destructor
		~Sum();
		void process();
	
	private:
		int i1, i2, oSum;
};

#endif // SUM_H
