// Class automatically generated by Dev-C++ New Class wizard

#ifndef AMPLIFIER_H
#define AMPLIFIER_H


#include "CBlock.h" // inheriting class's header file

/**
 * No description
 */
class Amplifier : public CBlock
{
	public:
		// class constructor
		Amplifier();
		// class destructor
		~Amplifier();
		// Process
		void Process(void);
};

#endif //AMPLIFIER_H

