// Class automatically generated by Dev-C++ New Class wizard

#include "gadsr.h" // class's header file

// class constructor
GADSR::GADSR( Module* mod ) :
	Gui( mod )
{
	slAttack.SetParameter( (ParameterFloat*)module->GetParameter( 0 ), 5, 2000, 1 );
	slDecay.SetParameter( (ParameterFloat*)module->GetParameter( 1 ), 5, 2000, 1 );
	slSustain.SetParameter( (ParameterFloat*)module->GetParameter( 2 ), 0, 0.99, 0.01 );
	slRelease.SetParameter( (ParameterFloat*)module->GetParameter( 3 ), 5, 2000, 1 );

	box.add( slAttack );
	box.add( slDecay );
	box.add( slSustain );
	box.add( slRelease );
}


GADSR::~GADSR() {
}

Gtk::Widget* GADSR::GetGui() {
	return &box;
}
